name: cocafe
description: "코딩하기 좋은 카페 추천앱"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  google_fonts: ^6.2.1
  flutter_naver_map: ^1.3.1
  geolocator: ^13.0.4
  geolocator_android: 4.6.0
  kakao_map_plugin: ^0.3.5
  shared_preferences: ^2.5.3
  geocoding: ^3.0.0
  http: ^1.3.0
  kakao_flutter_sdk: ^1.9.7+3
  image_picker: ^1.1.2
  flutter_reorderable_grid_view: ^5.5.0
  firebase_storage: ^12.4.5
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  path: ^1.9.0
  flutter_image_compress: ^2.4.0
  get_storage: ^2.1.1
  flutter_dotenv: ^5.2.1
  firebase_auth: ^5.5.3
  flutter_launcher_icons: ^0.14.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  assets:
    - asset/
    - asset/json/
    - .env
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "asset/app_icon.png" # 아이콘 경로
  remove_alpha_ios: true
