name: cocafe
description: "코딩하기 좋은 카페 추천앱"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  google_fonts: ^6.2.1
  flutter_naver_map: ^1.1.1
  geolocator: ^13.0.4
  geolocator_android: 4.6.0
  kakao_map_plugin: ^0.3.5
  shared_preferences: ^2.5.3
  geocoding: ^3.0.0
  http: ^1.3.0
  kakao_flutter_sdk: ^1.9.7+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  assets:
    - asset/json/
  uses-material-design: true


